<?php
/**
 * Self-updater backed by a GitHub branch (`release`).
 *
 * Hooks into the standard WordPress plugin-update flow so users see updates
 * in Plugins screen → Updates available, identical UX to plugins from the WP
 * repository. No external libraries.
 *
 * Release workflow (works through `git push` only — no GitHub UI step):
 *   1. Build the plugin and commit the runtime tree to the `release` branch
 *      with the plugin files at the branch root.
 *   2. Make sure smart-recurr-calendar.php on that branch carries the new
 *      Version: header.
 *   3. Push. Sites running an older version will see the update appear within
 *      12 hours, or instantly via the "Check for updates" plugin row link.
 *
 * Update detection:
 *   - GET raw.githubusercontent.com/<owner>/<repo>/release/smart-recurr-calendar.php
 *   - Parse the `Version:` plugin header.
 *   - If newer than the installed version, point WP at the auto-generated
 *     branch archive: github.com/<owner>/<repo>/archive/refs/heads/release.zip
 *   - upgrader_source_selection renames the extracted folder to match the
 *     installed plugin slug so the in-place upgrade is clean.
 *
 * @package SmartRecur
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class SmartRecur_Updater {

	const GITHUB_OWNER      = 'mamhuijb';
	const GITHUB_REPO       = 'Smart-Recurr-Calendar';
	const RELEASE_BRANCH    = 'release';
	const TRANSIENT_KEY     = 'smartrecur_latest_release';
	const TRANSIENT_TTL     = 12 * HOUR_IN_SECONDS;
	const FORCE_REFRESH_GET = 'smartrecur_force_update_check';

	/**
	 * Register all hooks.
	 */
	public static function register() {
		add_filter( 'pre_set_site_transient_update_plugins', array( __CLASS__, 'inject_update' ) );
		add_filter( 'plugins_api', array( __CLASS__, 'plugins_api' ), 10, 3 );
		add_filter( 'upgrader_source_selection', array( __CLASS__, 'fix_folder_name' ), 10, 4 );
		add_action( 'admin_init', array( __CLASS__, 'maybe_force_refresh' ) );
	}

	/**
	 * Plugin basename (matches `dirname/file.php`).
	 *
	 * @return string
	 */
	public static function plugin_basename() {
		return defined( 'SMARTRECUR_PLUGIN_BASENAME' ) ? SMARTRECUR_PLUGIN_BASENAME : 'smart-recurr-calendar/smart-recurr-calendar.php';
	}

	/**
	 * Plugin slug (folder name).
	 *
	 * @return string
	 */
	public static function plugin_slug() {
		return dirname( self::plugin_basename() );
	}

	/**
	 * Build the raw URL for the plugin header on the release branch.
	 *
	 * @return string
	 */
	private static function header_url() {
		return sprintf(
			'https://raw.githubusercontent.com/%s/%s/%s/smart-recurr-calendar.php',
			self::GITHUB_OWNER,
			self::GITHUB_REPO,
			self::RELEASE_BRANCH
		);
	}

	/**
	 * Build the GitHub branch archive URL — auto-generated by GitHub for any branch.
	 *
	 * @return string
	 */
	private static function zip_url() {
		return sprintf(
			'https://github.com/%s/%s/archive/refs/heads/%s.zip',
			self::GITHUB_OWNER,
			self::GITHUB_REPO,
			self::RELEASE_BRANCH
		);
	}

	/**
	 * Fetch the latest release manifest by reading the plugin header from the
	 * release branch. Caches the result for TRANSIENT_TTL.
	 *
	 * @param bool $force Bypass the cache.
	 * @return array|null Normalised release info, or null on failure.
	 */
	public static function get_latest_release( $force = false ) {
		if ( ! $force ) {
			$cached = get_transient( self::TRANSIENT_KEY );
			if ( is_array( $cached ) ) {
				return $cached;
			}
		}

		$response = wp_remote_get(
			self::header_url(),
			array(
				'timeout' => 10,
				'headers' => array(
					'User-Agent' => 'SmartRecur-Updater/' . SMARTRECUR_VERSION,
				),
			)
		);

		if ( is_wp_error( $response ) ) {
			set_transient( self::TRANSIENT_KEY, array( 'error' => $response->get_error_message() ), HOUR_IN_SECONDS );
			return null;
		}
		$code = (int) wp_remote_retrieve_response_code( $response );
		if ( $code < 200 || $code >= 300 ) {
			set_transient( self::TRANSIENT_KEY, array( 'error' => 'HTTP ' . $code ), HOUR_IN_SECONDS );
			return null;
		}

		$body    = (string) wp_remote_retrieve_body( $response );
		$version = '';
		if ( preg_match( '/^\s*\*?\s*Version:\s*(.+?)\s*$/mi', $body, $m ) ) {
			$version = trim( $m[1] );
		}
		if ( '' === $version ) {
			set_transient( self::TRANSIENT_KEY, array( 'error' => 'No Version: header on release branch' ), HOUR_IN_SECONDS );
			return null;
		}

		$normalised = array(
			'version'      => $version,
			'zip_url'      => self::zip_url(),
			'html_url'     => sprintf(
				'https://github.com/%s/%s/tree/%s',
				self::GITHUB_OWNER,
				self::GITHUB_REPO,
				self::RELEASE_BRANCH
			),
			'name'         => 'SmartRecur Calendar ' . $version,
			'published_at' => '',
		);
		set_transient( self::TRANSIENT_KEY, $normalised, self::TRANSIENT_TTL );
		return $normalised;
	}

	/**
	 * Inject our update entry into the WP plugins update transient.
	 *
	 * @param mixed $transient WP plugins update transient.
	 * @return mixed
	 */
	public static function inject_update( $transient ) {
		if ( ! is_object( $transient ) ) {
			return $transient;
		}

		$release = self::get_latest_release();
		if ( ! $release || empty( $release['version'] ) || empty( $release['zip_url'] ) ) {
			return $transient;
		}

		$current = SMARTRECUR_VERSION;
		if ( version_compare( $release['version'], $current, '<=' ) ) {
			if ( isset( $transient->response[ self::plugin_basename() ] ) ) {
				unset( $transient->response[ self::plugin_basename() ] );
			}
			$transient->no_update[ self::plugin_basename() ] = self::build_update_obj( $current, $release );
			return $transient;
		}

		$transient->response[ self::plugin_basename() ] = self::build_update_obj( $release['version'], $release );
		return $transient;
	}

	/**
	 * Build the std plugin update object that WP expects.
	 *
	 * @param string $version New version string.
	 * @param array  $release Normalised release info.
	 * @return object
	 */
	private static function build_update_obj( $version, array $release ) {
		return (object) array(
			'id'            => 'smartrecur/' . self::plugin_slug(),
			'slug'          => self::plugin_slug(),
			'plugin'        => self::plugin_basename(),
			'new_version'   => $version,
			'url'           => $release['html_url'],
			'package'       => $release['zip_url'],
			'icons'         => array(),
			'banners'       => array(),
			'banners_rtl'   => array(),
			'tested'        => '6.6',
			'requires_php'  => '8.4',
			'compatibility' => new stdClass(),
		);
	}

	/**
	 * "View details" popup data for the plugins screen.
	 *
	 * @param false|object|array $result Default false.
	 * @param string             $action API action.
	 * @param object             $args   Request args.
	 * @return false|object
	 */
	public static function plugins_api( $result, $action, $args ) {
		if ( 'plugin_information' !== $action ) {
			return $result;
		}
		if ( ! isset( $args->slug ) || $args->slug !== self::plugin_slug() ) {
			return $result;
		}

		$release = self::get_latest_release();
		if ( ! $release ) {
			return $result;
		}

		return (object) array(
			'name'           => 'SmartRecur Calendar',
			'slug'           => self::plugin_slug(),
			'version'        => $release['version'],
			'author'         => '<a href="https://github.com/' . esc_attr( self::GITHUB_OWNER ) . '">SmartRecur</a>',
			'homepage'       => 'https://github.com/' . self::GITHUB_OWNER . '/' . self::GITHUB_REPO,
			'requires'       => '6.0',
			'tested'         => '6.6',
			'requires_php'   => '8.4',
			'last_updated'   => '',
			'download_link'  => $release['zip_url'],
			'sections'       => array(
				'description' => '<p>' . esc_html__( 'Recurring appointment scheduler for MSPs with Office 365, Syncro, Invoice Ninja and Zoho integrations.', 'smartrecur' ) . '</p>',
				'changelog'   => '<p>' . esc_html(
					sprintf(
						/* translators: %1$s new version, %2$s branch name */
						__( 'Version %1$s available on the %2$s branch.', 'smartrecur' ),
						$release['version'],
						self::RELEASE_BRANCH
					)
				) . '</p><p><a href="' . esc_url( $release['html_url'] ) . '" target="_blank" rel="noopener">' . esc_html__( 'View the release branch on GitHub', 'smartrecur' ) . '</a></p>',
			),
		);
	}

	/**
	 * After WP downloads and extracts the branch archive (folder name like
	 * `Smart-Recurr-Calendar-release/`), rename it to match the installed
	 * plugin slug so the upgrade replaces the existing folder cleanly.
	 *
	 * @param string       $source        Extracted folder path.
	 * @param string       $remote_source Remote source path.
	 * @param WP_Upgrader  $upgrader      Upgrader instance.
	 * @param array        $hook_extra    Extra info about the upgrade.
	 * @return string|WP_Error
	 */
	public static function fix_folder_name( $source, $remote_source, $upgrader, $hook_extra = array() ) {
		if ( empty( $hook_extra['plugin'] ) || $hook_extra['plugin'] !== self::plugin_basename() ) {
			return $source;
		}

		$desired_leaf = self::plugin_slug();
		$current_leaf = basename( untrailingslashit( $source ) );
		if ( $current_leaf === $desired_leaf ) {
			return $source;
		}

		$new_source = trailingslashit( dirname( $source ) ) . $desired_leaf;

		global $wp_filesystem;
		if ( ! $wp_filesystem ) {
			require_once ABSPATH . 'wp-admin/includes/file.php';
			WP_Filesystem();
		}

		if ( $wp_filesystem && $wp_filesystem->move( $source, $new_source, true ) ) {
			return trailingslashit( $new_source );
		}

		return new WP_Error( 'smartrecur_rename_failed', __( 'SmartRecur updater: failed to rename extracted folder.', 'smartrecur' ) );
	}

	/**
	 * Bust the cache on demand via `?smartrecur_force_update_check=1`.
	 */
	public static function maybe_force_refresh() {
		if ( empty( $_GET[ self::FORCE_REFRESH_GET ] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
			return;
		}
		if ( ! current_user_can( 'update_plugins' ) ) {
			return;
		}
		delete_transient( self::TRANSIENT_KEY );
		delete_site_transient( 'update_plugins' );
		self::get_latest_release( true );
		wp_safe_redirect( remove_query_arg( self::FORCE_REFRESH_GET ) );
		exit;
	}
}

